name: GitHub Actions Demo

on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: python job.py
        env:
          SECRET_API_TOKEN: ${{ secrets.SECRET_API_TOKEN }}

      - run: echo "Fichier créé par GitHub Actions" > resultat.txt

      - uses: actions/upload-artifact@v4
        with:
          name: resultat
          path: resultat.txt